### ISSUE TITLE
Add block interval for fast_track mode

### ISSUE THREAD

**Issue by engn33r** [rainshowerLabs/sothis#17]
**Is your feature request related to a problem? Please describe.**

Instead of querying a state variable at every block, it would be great to add a tag to choose a block interval to allow a user to query every X blocks. This is useful if a user wants a summary of data over a longer timespan and does not want to wait for data from every block.

**Describe the solution you'd like**

Add a `--block_interval` flag to choose which blocks to query data from.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by makemake-kbo** [comment]
The one thing im worried about with this is it might add confusion. As long as its made _very_ clear that sothis will not get the full context, im fine with this.

**Comment by makemake-kbo** [comment]
Closing this as this feature has been added
