### ISSUE TITLE
Add csv output flag

### ISSUE THREAD

**Issue by engn33r** [rainshowerLabs/sothis#19]
**Is your feature request related to a problem? Please describe.**

Saving to an output file uses JSON format. Allowing CSV output can make it easier to analyze the data with certain tools, like spreadsheets.

**Describe the solution you'd like**

A flag to toggle the output format between JSON and CSV.

**Describe alternatives you've considered**

An external tool to convert JSON data to CSV data

**Additional context**

N/A

**Comment by makemake-kbo** [comment]
added in the 4.1.0 branch

**Comment by engn33r** [comment]
This is done, working in the current release
