### ISSUE TITLE
historic mode "Connection refused (os error 111)"

### ISSUE THREAD

**Issue by engn33r** [rainshowerLabs/sothis#6]
I am troubleshooting this error related to binding to a local port

```
sothis --source_rpc https://eth-mainnet.alchemyapi.io/v2/xxxx --replay_rpc http://127.0.0.1:8545 --terminal_block 17500000

Replaying in historic mode...
Error: JsonSerializationFailed("error sending request for url (http://127.0.0.1:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)")
```

**Comment by makemake-kbo** [comment]
I've been able to reproduce this by having the replay_rpc url not point to a local testnet node.
If the node is running, and the url is set correctly, this is likely a misconfiguration or an anvil bug.

**Comment by engn33r** [comment]
Ok this helps. I did not realize the local testnode had to be running at the reply_rpc URL. I was expecting sothis would launch a test node at that URL. When I start a test node at that URL before running sothis, everything works fine.

I would suggest updating the docs and improving the error message.

**Comment by makemake-kbo** [comment]
ill close the issue now and make it more clear that you need a node running at the replay_rpc url.

Having a node automatically start could be useful, but youd need to supply all the arguments for it with sothis so it might be clearer to just have more verbose error message.
